version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      POSTGRES_DB: my_company_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "5432:5432"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/my_company_db
      FLASK_DEBUG: 1
    depends_on:
      db:
        condition: service_healthy
